import type {
  MealPlan,
  GroceryList,
  BudgetData,
  CookingTask,
  Substitution,
} from "@/types";

// ─── Meal Plan ────────────────────────────────────────────────────────────────

export const mockMealPlan: MealPlan = {
  id: "mp-001",
  weekStart: "2026-06-13",
  weekEnd: "2026-06-19",
  totalCost: 127.5,
  totalCalories: 14280,
  days: [
    {
      date: "2026-06-13",
      dayName: "Saturday",
      breakfast: {
        id: "m-001",
        name: "Avocado Toast & Poached Eggs",
        type: "breakfast",
        description:
          "Creamy avocado on sourdough with perfectly poached eggs and everything bagel seasoning.",
        prepTime: 10,
        cookTime: 8,
        servings: 2,
        calories: 520,
        cost: 6.5,
        dietaryTags: ["vegetarian"],
        ingredients: [
          "2 slices sourdough",
          "1 avocado",
          "2 eggs",
          "Everything bagel seasoning",
          "Red pepper flakes",
        ],
        steps: [
          "Toast sourdough slices",
          "Mash avocado with salt and lemon",
          "Poach eggs for 3-4 minutes",
          "Assemble and season",
        ],
      },
      lunch: {
        id: "m-002",
        name: "Grilled Chicken Caesar Salad",
        type: "lunch",
        description:
          "Classic Caesar with housemade dressing, croutons, and grilled chicken breast.",
        prepTime: 15,
        cookTime: 12,
        servings: 2,
        calories: 680,
        cost: 9.5,
        dietaryTags: ["gluten-free", "high-protein"],
        ingredients: [
          "2 chicken breasts",
          "Romaine lettuce",
          "Parmesan",
          "Caesar dressing",
          "Croutons",
        ],
        steps: [
          "Season and grill chicken",
          "Chop romaine",
          "Toss with dressing",
          "Add toppings",
        ],
      },
      dinner: {
        id: "m-003",
        name: "Mushroom Risotto",
        type: "dinner",
        description:
          "Rich and creamy Italian risotto with wild mushrooms, white wine, and parmesan.",
        prepTime: 20,
        cookTime: 35,
        servings: 4,
        calories: 720,
        cost: 14.0,
        dietaryTags: ["vegetarian"],
        ingredients: [
          "Arborio rice",
          "Mixed mushrooms",
          "White wine",
          "Parmesan",
          "Vegetable stock",
          "Shallots",
        ],
        steps: [
          "Sauté shallots and garlic",
          "Toast rice",
          "Add wine then stock gradually",
          "Stir in mushrooms and parmesan",
        ],
      },
    },
    {
      date: "2026-06-14",
      dayName: "Sunday",
      breakfast: {
        id: "m-004",
        name: "Acai Berry Smoothie Bowl",
        type: "breakfast",
        description:
          "Vibrant acai smoothie bowl topped with fresh berries, granola, and honey drizzle.",
        prepTime: 10,
        cookTime: 0,
        servings: 1,
        calories: 420,
        cost: 5.5,
        dietaryTags: ["vegan", "gluten-free"],
        ingredients: [
          "Acai packets",
          "Mixed berries",
          "Banana",
          "Granola",
          "Honey",
          "Coconut flakes",
        ],
        steps: ["Blend acai with banana", "Pour into bowl", "Add toppings"],
      },
      lunch: {
        id: "m-005",
        name: "Veggie Buddha Bowl",
        type: "lunch",
        description:
          "Nourishing bowl with roasted veggies, quinoa, chickpeas, and tahini dressing.",
        prepTime: 20,
        cookTime: 25,
        servings: 2,
        calories: 590,
        cost: 8.0,
        dietaryTags: ["vegan", "gluten-free", "high-protein"],
        ingredients: [
          "Quinoa",
          "Chickpeas",
          "Sweet potato",
          "Kale",
          "Tahini",
          "Lemon",
        ],
        steps: [
          "Cook quinoa",
          "Roast veggies at 400F",
          "Prepare tahini dressing",
          "Assemble bowls",
        ],
      },
      dinner: {
        id: "m-006",
        name: "Salmon Teriyaki",
        type: "dinner",
        description:
          "Glazed salmon fillet with homemade teriyaki sauce, steamed rice, and broccolini.",
        prepTime: 15,
        cookTime: 15,
        servings: 2,
        calories: 650,
        cost: 18.0,
        dietaryTags: ["gluten-free", "high-protein", "dairy-free"],
        ingredients: [
          "Salmon fillets",
          "Soy sauce",
          "Mirin",
          "Honey",
          "Ginger",
          "Garlic",
          "Jasmine rice",
          "Broccolini",
        ],
        steps: [
          "Mix teriyaki sauce",
          "Marinate salmon",
          "Pan-sear salmon",
          "Glaze and finish",
          "Serve with rice",
        ],
      },
    },
    {
      date: "2026-06-15",
      dayName: "Monday",
      breakfast: {
        id: "m-007",
        name: "Greek Yogurt Parfait",
        type: "breakfast",
        description:
          "Layers of Greek yogurt, mixed berry compote, and crunchy honey granola.",
        prepTime: 5,
        cookTime: 0,
        servings: 1,
        calories: 380,
        cost: 4.0,
        dietaryTags: ["vegetarian", "high-protein"],
        ingredients: [
          "Greek yogurt",
          "Mixed berries",
          "Granola",
          "Honey",
          "Chia seeds",
        ],
        steps: ["Layer yogurt", "Add berries", "Top with granola and honey"],
      },
      lunch: {
        id: "m-008",
        name: "Turkey & Avocado Wrap",
        type: "lunch",
        description:
          "Whole wheat wrap with turkey, avocado, tomato, and chipotle mayo.",
        prepTime: 10,
        cookTime: 0,
        servings: 1,
        calories: 540,
        cost: 7.0,
        dietaryTags: ["dairy-free"],
        ingredients: [
          "Whole wheat tortilla",
          "Turkey slices",
          "Avocado",
          "Tomato",
          "Lettuce",
          "Chipotle mayo",
        ],
        steps: [
          "Spread chipotle mayo",
          "Layer ingredients",
          "Roll tightly",
          "Slice diagonally",
        ],
      },
      dinner: {
        id: "m-009",
        name: "Pasta Primavera",
        type: "dinner",
        description:
          "Light pasta with seasonal vegetables in a white wine garlic sauce.",
        prepTime: 15,
        cookTime: 20,
        servings: 4,
        calories: 580,
        cost: 10.0,
        dietaryTags: ["vegetarian"],
        ingredients: [
          "Penne pasta",
          "Zucchini",
          "Cherry tomatoes",
          "Bell peppers",
          "White wine",
          "Garlic",
          "Parmesan",
        ],
        steps: [
          "Cook pasta al dente",
          "Sauté garlic and vegetables",
          "Deglaze with wine",
          "Toss pasta with sauce",
        ],
      },
    },
    {
      date: "2026-06-16",
      dayName: "Tuesday",
      breakfast: {
        id: "m-010",
        name: "Overnight Oats",
        type: "breakfast",
        description:
          "Creamy overnight oats with almond milk, chia seeds, and fresh mango.",
        prepTime: 5,
        cookTime: 0,
        servings: 1,
        calories: 420,
        cost: 3.5,
        dietaryTags: ["vegan", "gluten-free"],
        ingredients: [
          "Rolled oats",
          "Almond milk",
          "Chia seeds",
          "Mango",
          "Maple syrup",
        ],
        steps: ["Mix oats with milk", "Add chia seeds", "Refrigerate overnight", "Top with mango"],
      },
      dinner: {
        id: "m-011",
        name: "Chicken Tikka Masala",
        type: "dinner",
        description:
          "Tender chicken in a rich, spiced tomato-cream sauce served with basmati rice.",
        prepTime: 20,
        cookTime: 30,
        servings: 4,
        calories: 720,
        cost: 16.0,
        dietaryTags: ["gluten-free", "high-protein"],
        ingredients: [
          "Chicken thighs",
          "Tikka masala paste",
          "Diced tomatoes",
          "Heavy cream",
          "Basmati rice",
          "Cilantro",
        ],
        steps: [
          "Marinate and cook chicken",
          "Prepare sauce",
          "Combine and simmer",
          "Serve with rice",
        ],
      },
    },
    {
      date: "2026-06-17",
      dayName: "Wednesday",
      breakfast: {
        id: "m-012",
        name: "Banana Pancakes",
        type: "breakfast",
        description: "Fluffy banana pancakes with maple syrup and fresh blueberries.",
        prepTime: 10,
        cookTime: 15,
        servings: 2,
        calories: 480,
        cost: 5.0,
        dietaryTags: ["vegetarian"],
        ingredients: ["Bananas", "Eggs", "Flour", "Milk", "Baking powder", "Maple syrup", "Blueberries"],
        steps: ["Mash bananas", "Mix batter", "Cook on griddle", "Serve with toppings"],
      },
      dinner: {
        id: "m-013",
        name: "Black Bean Tacos",
        type: "dinner",
        description: "Crispy black bean tacos with mango salsa and avocado crema.",
        prepTime: 20,
        cookTime: 15,
        servings: 4,
        calories: 520,
        cost: 9.0,
        dietaryTags: ["vegan", "gluten-free"],
        ingredients: ["Black beans", "Corn tortillas", "Mango", "Red onion", "Cilantro", "Avocado", "Lime"],
        steps: ["Season and heat beans", "Make mango salsa", "Blend avocado crema", "Assemble tacos"],
      },
    },
    {
      date: "2026-06-18",
      dayName: "Thursday",
      breakfast: {
        id: "m-014",
        name: "Veggie Omelette",
        type: "breakfast",
        description: "Fluffy three-egg omelette loaded with peppers, spinach, and feta.",
        prepTime: 10,
        cookTime: 10,
        servings: 1,
        calories: 420,
        cost: 4.5,
        dietaryTags: ["vegetarian", "gluten-free"],
        ingredients: ["Eggs", "Bell peppers", "Spinach", "Feta cheese", "Olive oil"],
        steps: ["Whisk eggs", "Sauté veggies", "Pour eggs over veggies", "Add feta and fold"],
      },
      dinner: {
        id: "m-015",
        name: "Beef Stir-Fry",
        type: "dinner",
        description: "Quick beef stir-fry with seasonal vegetables in a savory ginger sauce.",
        prepTime: 15,
        cookTime: 12,
        servings: 3,
        calories: 680,
        cost: 19.0,
        dietaryTags: ["dairy-free", "high-protein"],
        ingredients: ["Beef sirloin", "Broccoli", "Snap peas", "Carrots", "Soy sauce", "Ginger", "Garlic", "Sesame oil"],
        steps: ["Slice beef thin", "Prep vegetables", "High heat stir-fry", "Add sauce and toss"],
      },
    },
    {
      date: "2026-06-19",
      dayName: "Friday",
      breakfast: {
        id: "m-016",
        name: "Chia Pudding",
        type: "breakfast",
        description: "Creamy coconut chia pudding with passion fruit and toasted coconut.",
        prepTime: 5,
        cookTime: 0,
        servings: 2,
        calories: 340,
        cost: 4.5,
        dietaryTags: ["vegan", "gluten-free", "dairy-free"],
        ingredients: ["Chia seeds", "Coconut milk", "Passion fruit", "Maple syrup", "Toasted coconut"],
        steps: ["Mix chia with coconut milk", "Refrigerate overnight", "Top with fruit"],
      },
      dinner: {
        id: "m-017",
        name: "Shrimp Scampi",
        type: "dinner",
        description: "Classic shrimp scampi with linguine, garlic, white wine, and lemon.",
        prepTime: 15,
        cookTime: 15,
        servings: 4,
        calories: 620,
        cost: 22.0,
        dietaryTags: ["dairy-free", "high-protein"],
        ingredients: ["Shrimp", "Linguine", "Garlic", "White wine", "Lemon", "Parsley", "Olive oil"],
        steps: ["Cook linguine", "Sauté garlic", "Add shrimp and wine", "Finish with lemon"],
      },
    },
  ],
};

// ─── Grocery List ─────────────────────────────────────────────────────────────

export const mockGroceryList: GroceryList = {
  id: "gl-001",
  weekStart: "2026-06-13",
  totalEstimated: 94.5,
  totalActual: 87.3,
  items: [
    { id: "g-001", name: "Sourdough bread", category: "grains", quantity: 1, unit: "loaf", estimatedPrice: 4.5, checked: true },
    { id: "g-002", name: "Avocados", category: "produce", quantity: 4, unit: "pcs", estimatedPrice: 6.0, checked: true },
    { id: "g-003", name: "Free-range eggs", category: "dairy", quantity: 12, unit: "pcs", estimatedPrice: 5.5, checked: true },
    { id: "g-004", name: "Chicken breasts", category: "proteins", quantity: 4, unit: "lbs", estimatedPrice: 16.0, checked: false },
    { id: "g-005", name: "Salmon fillets", category: "proteins", quantity: 2, unit: "pcs", estimatedPrice: 18.0, checked: false },
    { id: "g-006", name: "Mixed mushrooms", category: "produce", quantity: 1, unit: "lb", estimatedPrice: 5.0, checked: true },
    { id: "g-007", name: "Arborio rice", category: "grains", quantity: 1, unit: "lb", estimatedPrice: 4.0, checked: true },
    { id: "g-008", name: "Cherry tomatoes", category: "produce", quantity: 1, unit: "pint", estimatedPrice: 3.5, checked: false },
    { id: "g-009", name: "Greek yogurt", category: "dairy", quantity: 32, unit: "oz", estimatedPrice: 6.5, checked: true },
    { id: "g-010", name: "Quinoa", category: "grains", quantity: 1, unit: "lb", estimatedPrice: 5.5, checked: false },
    { id: "g-011", name: "Chickpeas (canned)", category: "pantry", quantity: 2, unit: "cans", estimatedPrice: 2.5, checked: true },
    { id: "g-012", name: "Almond milk", category: "beverages", quantity: 0.5, unit: "gallon", estimatedPrice: 4.0, checked: false },
    { id: "g-013", name: "Chia seeds", category: "pantry", quantity: 8, unit: "oz", estimatedPrice: 5.0, checked: true },
    { id: "g-014", name: "Beef sirloin", category: "proteins", quantity: 1.5, unit: "lbs", estimatedPrice: 19.0, checked: false },
    { id: "g-015", name: "Shrimp (peeled)", category: "proteins", quantity: 1, unit: "lb", estimatedPrice: 14.0, checked: false },
  ],
};

// ─── Budget ───────────────────────────────────────────────────────────────────

export const mockBudgetData: BudgetData = {
  id: "b-001",
  month: "June 2026",
  totalBudget: 450,
  totalSpent: 312.4,
  categories: [
    { id: "bc-001", name: "Proteins", budgeted: 140, spent: 98.5, color: "hsl(221, 83%, 53%)" },
    { id: "bc-002", name: "Produce", budgeted: 80, spent: 54.3, color: "hsl(142, 76%, 36%)" },
    { id: "bc-003", name: "Grains & Pantry", budgeted: 70, spent: 52.1, color: "hsl(35, 92%, 50%)" },
    { id: "bc-004", name: "Dairy & Eggs", budgeted: 60, spent: 48.7, color: "hsl(262, 83%, 58%)" },
    { id: "bc-005", name: "Beverages", budgeted: 40, spent: 28.4, color: "hsl(340, 82%, 52%)" },
    { id: "bc-006", name: "Other", budgeted: 60, spent: 30.4, color: "hsl(199, 89%, 48%)" },
  ],
  weeklyBreakdown: [
    { week: "Jun 1-7", budgeted: 112.5, spent: 108.2 },
    { week: "Jun 8-14", budgeted: 112.5, spent: 94.5 },
    { week: "Jun 15-21", budgeted: 112.5, spent: 109.7 },
    { week: "Jun 22-30", budgeted: 112.5, spent: 0 },
  ],
};

// ─── Cooking Tasks ────────────────────────────────────────────────────────────

export const mockCookingTasks: CookingTask[] = [
  {
    id: "ct-001",
    title: "Prep mushroom risotto base",
    description: "Dice shallots, mince garlic, clean and slice mushrooms. Warm stock.",
    mealId: "m-003",
    mealName: "Mushroom Risotto",
    estimatedMinutes: 20,
    priority: "high",
    status: "todo",
    scheduledFor: "2026-06-13T17:30:00",
    steps: [
      "Dice 3 shallots finely",
      "Mince 4 garlic cloves",
      "Clean and slice 500g mixed mushrooms",
      "Warm 4 cups vegetable stock in a saucepan",
    ],
    tags: ["prep", "mise-en-place"],
  },
  {
    id: "ct-002",
    title: "Marinate salmon for teriyaki",
    description: "Prepare teriyaki marinade and marinate salmon for 30 minutes.",
    mealId: "m-006",
    mealName: "Salmon Teriyaki",
    estimatedMinutes: 35,
    priority: "high",
    status: "in-progress",
    scheduledFor: "2026-06-14T17:00:00",
    steps: [
      "Mix 3 tbsp soy sauce, 2 tbsp mirin, 1 tbsp honey",
      "Add grated ginger and garlic",
      "Pat salmon dry and place in marinade",
      "Refrigerate for 30 minutes",
    ],
    tags: ["marinade", "prep"],
  },
  {
    id: "ct-003",
    title: "Cook overnight oats",
    description: "Prepare overnight oats the evening before for Tuesday breakfast.",
    mealId: "m-010",
    mealName: "Overnight Oats",
    estimatedMinutes: 5,
    priority: "medium",
    status: "done",
    scheduledFor: "2026-06-15T20:00:00",
    steps: [
      "Combine 1/2 cup oats with 1 cup almond milk",
      "Stir in 1 tbsp chia seeds",
      "Add maple syrup to taste",
      "Refrigerate overnight",
    ],
    tags: ["prep-ahead", "breakfast"],
  },
  {
    id: "ct-004",
    title: "Make chicken tikka marinade",
    description: "Prepare the yogurt-spice marinade and marinate chicken overnight.",
    mealId: "m-011",
    mealName: "Chicken Tikka Masala",
    estimatedMinutes: 15,
    priority: "medium",
    status: "todo",
    scheduledFor: "2026-06-16T19:00:00",
    steps: [
      "Mix yogurt with tikka masala paste",
      "Add salt, garam masala, turmeric",
      "Coat chicken pieces thoroughly",
      "Refrigerate minimum 2 hours",
    ],
    tags: ["marinade", "prep-ahead"],
  },
  {
    id: "ct-005",
    title: "Prep stir-fry vegetables",
    description: "Slice beef and cut all vegetables for Wednesday stir-fry.",
    mealId: "m-015",
    mealName: "Beef Stir-Fry",
    estimatedMinutes: 25,
    priority: "low",
    status: "todo",
    scheduledFor: "2026-06-18T16:30:00",
    steps: [
      "Slice beef thinly against the grain",
      "Cut broccoli into florets",
      "Trim snap peas",
      "Julienne carrots",
      "Mix sauce ingredients",
    ],
    tags: ["prep", "mise-en-place"],
  },
];

// ─── Substitutions ────────────────────────────────────────────────────────────

export const mockSubstitutions: Substitution[] = [
  {
    id: "s-001",
    original: "Heavy Cream",
    category: "dairy",
    reason: "dairy-free",
    alternatives: [
      {
        name: "Coconut Cream",
        ratio: "1:1",
        notes: "Use full-fat coconut cream for best results. Adds a subtle coconut flavor.",
        dietaryTags: ["vegan", "dairy-free"],
      },
      {
        name: "Cashew Cream",
        ratio: "1:1",
        notes: "Soak and blend cashews with water. Neutral flavor, very creamy.",
        dietaryTags: ["vegan", "dairy-free"],
      },
      {
        name: "Oat Milk (thickened)",
        ratio: "1:1",
        notes: "Use barista oat milk or reduce slightly for thicker consistency.",
        dietaryTags: ["vegan", "dairy-free"],
      },
    ],
  },
  {
    id: "s-002",
    original: "Butter",
    category: "dairy",
    reason: "dairy-free",
    alternatives: [
      {
        name: "Vegan Butter",
        ratio: "1:1",
        notes: "Best 1:1 swap. Works in baking and cooking.",
        dietaryTags: ["vegan", "dairy-free"],
      },
      {
        name: "Olive Oil",
        ratio: "3/4 cup per 1 cup",
        notes: "Better for sautéing and roasting than baking.",
        dietaryTags: ["vegan", "dairy-free"],
      },
      {
        name: "Avocado Oil",
        ratio: "3/4 cup per 1 cup",
        notes: "High smoke point, great for high-heat cooking.",
        dietaryTags: ["vegan", "dairy-free"],
      },
    ],
  },
  {
    id: "s-003",
    original: "Parmesan Cheese",
    category: "dairy",
    reason: "dairy-free",
    alternatives: [
      {
        name: "Nutritional Yeast",
        ratio: "3 tbsp per 1/4 cup",
        notes: "Provides umami and cheesy flavor. Reduce salt as it's quite savory.",
        dietaryTags: ["vegan", "dairy-free", "gluten-free"],
      },
      {
        name: "Cashew Parmesan",
        ratio: "1:1",
        notes: "Blend cashews, nutritional yeast, garlic powder, and salt.",
        dietaryTags: ["vegan", "dairy-free", "gluten-free"],
      },
    ],
  },
  {
    id: "s-004",
    original: "All-Purpose Flour",
    category: "grains",
    reason: "gluten-free",
    alternatives: [
      {
        name: "Almond Flour",
        ratio: "1:1 for most recipes",
        notes: "Denser texture. Best for pancakes, muffins. Not ideal for bread.",
        dietaryTags: ["gluten-free", "low-carb"],
      },
      {
        name: "Oat Flour",
        ratio: "1:1",
        notes: "Use certified GF oats. Slightly denser, great for baked goods.",
        dietaryTags: ["gluten-free"],
      },
      {
        name: "Rice Flour",
        ratio: "1:1",
        notes: "Very light texture. Often combined with other GF flours.",
        dietaryTags: ["gluten-free"],
      },
    ],
  },
  {
    id: "s-005",
    original: "Soy Sauce",
    category: "condiments",
    reason: "gluten-free",
    alternatives: [
      {
        name: "Tamari",
        ratio: "1:1",
        notes: "Best 1:1 substitute. Same depth of flavor, certified gluten-free.",
        dietaryTags: ["gluten-free", "dairy-free"],
      },
      {
        name: "Coconut Aminos",
        ratio: "1:1",
        notes: "Slightly sweeter and lower sodium. Great for dressings.",
        dietaryTags: ["gluten-free", "dairy-free", "vegan"],
      },
    ],
  },
];
